version: "3"
services:
  manager:
    image: coursework/manager:1.0.0
    ports:
      - "18081:18081"
    environment:
      MSS_MANAGER_PORT: 18081
      MSS_KAFKA_BOOTSTRAP_SERVERS: 172.16.185.205:29092